[project]
name = "postgresql-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "psycopg2-binary>=2.9.11",
    "tabulate>=0.9.0",
]
